export enum Role {
  ADMIN = 'ADMIN',
  MEDICO = 'MEDICO',
  ENFERMEIRO = 'ENFERMEIRO',
  AUXILIAR_ENFERMAGEM = 'AUXILIAR_ENFERMAGEM',
  TECNICO_ENFERMAGEM = 'TECNICO_ENFERMAGEM',
  ESTAGIARIO = 'ESTAGIARIO',
}
